// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiSJXq1KEdpdVAEf5_OeLTDKcOFIIrSfo',
    appId: '1:751872125098:web:e9111004993d52172c88d3',
    messagingSenderId: '751872125098',
    projectId: 'bilingual-buddy-18512',
    authDomain: 'bilingual-buddy-18512.firebaseapp.com',
    storageBucket: 'bilingual-buddy-18512.firebasestorage.app',
    measurementId: 'G-DSL635VPMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8REUvioBsmZwwTRb4t4z3UC5u3XPxLE',
    appId: '1:751872125098:android:7350ab52ad428f6a2c88d3',
    messagingSenderId: '751872125098',
    projectId: 'bilingual-buddy-18512',
    storageBucket: 'bilingual-buddy-18512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT2WgZThi0SFvTa29-9WjLrIANtWvGc0Q',
    appId: '1:751872125098:ios:64364f8d67313bb22c88d3',
    messagingSenderId: '751872125098',
    projectId: 'bilingual-buddy-18512',
    storageBucket: 'bilingual-buddy-18512.firebasestorage.app',
    iosBundleId: 'com.example.bilingualBuddy',
  );

}